### PR TITLE
Added check for SSBSWM into spawn check

### PR DESCRIPTION
**Pull request by Paul19988**
Adding in this check avoids the server shutting down when it can't find the world whilst SSBSWM is generating it.

### CODE REVIEW

**Comment by OmerBenGera** [comment]
I don't understand what it fixes. You just removed the check for the world if the SlimeWorldManager is installed without doing any additional checks.
Mind explaining the original issue?

**Comment by Paul19988** [comment]
The original issue would come when SSB would check for the spawn world it would just shutdown the server however the world may still exist in SWM it just hasn't loaded yet

**Comment by OmerBenGera** [comment]
> 
> 
> The original issue would come when SSB would check for the spawn world it would just shutdown the server however the world may still exist in SWM it just hasn't loaded yet

But wait, performance wise, isn't it better to just have the spawn loaded all the time?

**Comment by Paul19988** [comment]
Typically in most cases it would already be loaded other than on first boot where the world needs to be created

**Comment by OmerBenGera** [comment]
We talked on Discord, will be implemented soon

**Pull request closed without merging**
